- name: Gather info about containers
  hosts: docker
  gather_facts: True
  tasks:
    - name: Get facts about containers
      local_action:
        module: docker_facts
        images: all

    - name: containers debug info
      debug: msg="Container Name {{ item.key }} IP Address {{ item.value.docker_networksettings.IPAddress }}"
      with_dict: docker_containers

    - name: images info
      debug: msg="Image ID {{ item.key }} Author {{ item.value.docker_author }} Repo Tags {{ item.value.docker_repotags }}"
      with_dict: docker_images
