- name: Gather info about containers
  hosts: "{{ hosts }}" 
  gather_facts: True
  tasks:
    - name: Get facts about containers
      local_action:
        docker_url: tcp://{{ inventory_hostname }}:4243
        module: docker_facts
        images: all

    - name: images info
      debug: msg="Image ID {{ item.key }} Repo Tags {{ item.value.docker_repotags }}"
      with_dict: docker_images
