- hosts: "{{ hosts }}"
  gather_facts: False
  vars:
    containers_count: 10 
  roles:
  - common
  - web

- hosts: "{{ hosts }}"
  gather_facts: False
  vars:
    containers_count: 3
  roles:
  - common
  - db

- hosts: "{{ hosts }}"
  gather_facts: False
  vars:
    containers_count: 4 
  roles:
  - common
  - haproxy
